name: PlatformIO CI

on:
  workflow_call:
  push:
    branches: [main]

jobs:
  build-bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build bootstrap
        run: pio run
